dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.13.x"
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on

install:

script:
- make test
- make vet
- make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
